Lab-2.3 An introduction to necessary tools in numpy

Some basic syntax for defining arrays, and access their useful attributes

In [4]:
import numpy as np
#defining arrays 
x_1 = np.array([1,2,3,4])
x_2 = np.array([[1,2],
                [3,4]], dtype='float64')
print('x_1 ans x_2 are as following', '\n',x_1,'\n',x_2)
    

x_1 ans x_2 are as following 
 [1 2 3 4] 
 [[1. 2.]
 [3. 4.]]


In [8]:
# Useful attributes for an array
print('x_1 has dimension',x_1.ndim,',while x_2 has dimension',x_2.ndim) 
print('data type:',x_1.dtype,x_2.dtype)
print('the shape are as following', x_1.shape,'and',x_2.shape)

x_1 has dimension 1 ,while x_2 has dimension 2
data type: int64 float64
the shape are as following (4,) and (2, 2)


For accessing the different values of an array, we work inwards, from outer layer to inner layer. Often with bracket notation. The difference is creating or manipulating one array. 

In [16]:
A = np.array([1,2,3])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
[[10,11,12],[13,14,15],[16,17,18]]
D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

print('A:',A,'\n','B:',B,'\n','C:',C,'\n D:',D)



A: [1 2 3] 
 B: [[1 2 3]
 [4 5 6]] 
 C: [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 D: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
# access individual elements
print('test 1:',A[0],B[1][1],C[2][2],D[1][2][0])
print('test 1.1:',A[0],B[1,1],C[2,2],D[1,2,0])

#slicing of rows columns etc
print('test 2:',A[1:])
print('test 3:',B[1][1:3]) # access withing a row
print('test 3.1:',B[1,1:3]) # access withing a row

print('test 4:',C[0:2,0])
print('test 4.1 not same!:',C[0:2][0])

# selection of rows an column with lists
print('V2: test 2:',A[[1,2]])
print('v2 test 3:',B[[1],[1,2]]) # access withing a row
print('V2 test 4:', C[[0,1],[0]])

print('Combine test!:', C[[0,2]][:,[0,2]])

# 3 d array
print('3D test 1:', D[1,1,1]) # pick out one
# pick a column/row withing a layer
print('3D test 2.1:', D[1,:,1]) 
print('3D test 2.2:', D[1,2,:]) 
# pick a 'staple', then a wall, group pillar
print('3D test 3.1:', D[:,1,1]) 
print('3D test 3.2:', D[:,:,0]) 
print('3D combine test:', D[:,[0,2]][:,:,[0,2]])

# follow on with some reshaping of the 'pillar'
print('3D combine test with reshape \n :',
       D[:,[0,2]][:,:,[0,2]].reshape([4,2]))

test 1: 1 5 9 16
test 1.1: 1 5 9 16
test 2: [2 3]
test 3: [5 6]
test 3.1: [5 6]
test 4: [1 4]
test 4.1 not same!: [1 2 3]
V2: test 2: [2 3]
v2 test 3: [5 6]
V2 test 4: [1 4]
Combine test!: [[1 3]
 [7 9]]
3D test 1: 14
3D test 2.1: [11 14 17]
3D test 2.2: [16 17 18]
3D test 3.1: [ 5 14]
3D test 3.2: [[ 1  4  7]
 [10 13 16]]
3D combine test: [[[ 1  3]
  [ 7  9]]

 [[10 12]
  [16 18]]]
3D combine test with reashape 
 : [[ 1  3]
 [ 7  9]
 [10 12]
 [16 18]]


In contrast to accessing values, why may also change the size of a numpy array but keeping the same elements

In [ ]:
# transform from 1 d array
x = np.array([1, 2, 3, 4, 5, 6])
print('original x', x)
x_r1=x.reshape([2,3])
x_r2 = x.reshape([2,3,1])
print('test 1.1',x_r1)
print('test 1.2',x_r2)

# transform from 2d array
y = np.array([[1, 2, 3, 4,5,6 ],[7, 8, 9, 10,11,12]])
print('original y \n', y)
y_r1 = y.reshape([4,3])
y_r2 = y.reshape([12,-1]) # negative 1 means that she system figures out that dimension 
y_r3 = y.reshape([3,2,2])
print('test 2.1',y_r1)
print('test 2.2',y_r2)
print('test 2.3', y_r3)



The Reshape method of arrays is Greeley a viewing object, so remember to copy it for it to be not tangled. 

In [118]:

A = np.array([1,2,3,4,5,6])
A_reshape = A.reshape([3,2])
A_reshape_copy = A.reshape([3,2]).copy()
print(A,'\n',A_reshape,'\n',A_reshape_copy)

A[2] = 100
print(A,'\n', A_reshape,'\n',A_reshape_copy)


print(np.shares_memory(A,A_reshape))
print(np.shares_memory(A,A_reshape_copy))

[1 2 3 4 5 6] 
 [[1 2]
 [3 4]
 [5 6]] 
 [[1 2]
 [3 4]
 [5 6]]
[  1   2 100   4   5   6] 
 [[  1   2]
 [100   4]
 [  5   6]] 
 [[1 2]
 [3 4]
 [5 6]]
True
False


Operation: Numpy arrays are useful since it is possible to preforms mathematical operations on their elements

In [141]:
import math

In [144]:

A = np.array([[1,2,3,4,5,8,math.pi /2,math.e]])
B = np.array([[1,2,3],[4,5,6]])

# basic arethmatics
print('addition and multiplication:',A+3,2*A)
print('addition and multiplication:',B+2,3*B)
print('division',2/B,B/2)

# upper level artichmatics
print('exponent, as base', A**3)
print('roots', A**(1/3))
print('exponent, as exponent',2**A)

print('comparison test', A**(-1/2), (1/A)**(1/2), A**(-1/2)== (1/A)**(1/2) )

# log and trigonometric

print(np.sin(A))
print(np.log(A))


addition and multiplication: [[ 4.          5.          6.          7.          8.         11.
   4.57079633  5.71828183]] [[ 2.          4.          6.          8.         10.         16.
   3.14159265  5.43656366]]
addition and multiplication: [[3 4 5]
 [6 7 8]] [[ 3  6  9]
 [12 15 18]]
division [[2.         1.         0.66666667]
 [0.5        0.4        0.33333333]] [[0.5 1.  1.5]
 [2.  2.5 3. ]]
exponent, as base [[  1.           8.          27.          64.         125.
  512.           3.87578459  20.08553692]]
roots [[1.         1.25992105 1.44224957 1.58740105 1.70997595 2.
  1.16244735 1.39561243]]
exponent, as exponent [[  2.           4.           8.          16.          32.
  256.           2.97068642   6.58088599]]
comparison test [[1.         0.70710678 0.57735027 0.5        0.4472136  0.35355339
  0.79788456 0.60653066]] [[1.         0.70710678 0.57735027 0.5        0.4472136  0.35355339
  0.79788456 0.60653066]] [[ True  True  True  True  True  True  True  True]]
[[ 0.

In [159]:
# operations between two 

A = np.array([[1,2,3],[5,6,7],[9,10,11]])
B = np.array([[1,0],[0,1],[1,0]])
B_1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
try:
    print(A+B)
except:
    print('wrong dimension')
print(A+B_1) #addition
print(A@B)   # matrix multiplication  (n,k)@(k,m) --> (n,m)  remember

x = np.array([[1,2],[2,4]])
y =  np.array([[1,2],[4,4]])
try:
    print('inverses',np.linalg.inv(x))
except:
    print('singular matrix')

print('inverses',np.linalg.inv(y), y@np.linalg.inv(y))
    


wrong dimension
[[ 2  2  3]
 [ 5  7  7]
 [ 9 10 12]]
[[ 4  2]
 [12  6]
 [20 10]]
singular matrix
inverses [[-1.    0.5 ]
 [ 1.   -0.25]] [[1. 0.]
 [0. 1.]]


Random package are important in the context of statical learning, since they model the randomness of the world .

In [160]:
import random

In [ ]:
# uniform number between [0,1)
from os import replace


print(random.random())
print(np.random.random())

#random integer between two integers 
print(random.randrange(-5,5)) # exclusive of end point
print(np.random.random_integers(-5,5)) # inclusive of end point

#random floating point value in a range [a,b)
print(random.uniform(math.pi,2*math.pi))
print(np.random.uniform(math.pi,2*math.pi))

#random element of a list
A = [1,2,3]
A_1 = np.array(A)
print(random.choice(A))
print(np.random.choice(A_1))

# multiple elements from list
print(random.sample(A,k=2)) # without replacement
print(random.choices(A,k=2)) # with replacement

weights=[0.9,0.05,0.05]
print(np.random.choice(A_1,size=[2,2],replace=True,p=weights))

print(random.choices(A,k=2,weights=weights)) # with replacement


0.526530154480145
0.6098827229642366
-2
-2
3.3225387412941423
4.105921125706981
1
1
[2, 3]
[1, 1]
[[1 3]
 [1 1]]
[1, 1]


C:\Users\abdir\AppData\Local\Temp\ipykernel_34340\2448063737.py:10: DeprecationWarning: This function is deprecated. Please call randint(-5, 5 + 1) instead
  print(np.random.random_integers(-5,5)) # inclusive of end point


following on the random theme, we may want to model a random process which isn't just uniform, the most common being a normal Gaussian distribution. 

In [245]:
A = np.random.normal(loc=0,scale=1,size=[50,1])
print(A)

[[ 1.0264674 ]
 [-1.05469494]
 [ 2.50853873]
 [-0.28285246]
 [-1.31785527]
 [-0.59711227]
 [-1.00051336]
 [ 0.93952738]
 [ 0.6703996 ]
 [ 0.6449003 ]
 [-0.55276646]
 [-0.8182591 ]
 [ 0.7564794 ]
 [ 0.75452276]
 [ 1.00515051]
 [-1.21742131]
 [-0.88847416]
 [-0.96583863]
 [ 0.46314752]
 [ 0.16069927]
 [ 0.13223494]
 [-0.29452302]
 [-0.24949142]
 [-1.04465905]
 [-0.52420808]
 [-0.07650099]
 [-1.23937655]
 [-0.95105377]
 [ 0.19973181]
 [-0.77685588]
 [ 0.22930822]
 [-0.33605091]
 [ 2.2276959 ]
 [ 0.90011247]
 [ 0.83546656]
 [-0.5261151 ]
 [-0.87086265]
 [ 1.30828209]
 [ 0.3312643 ]
 [-2.08804398]
 [-1.72900955]
 [ 0.8861027 ]
 [-0.811991  ]
 [-0.71349949]
 [-0.23781858]
 [ 0.04408716]
 [ 2.3489088 ]
 [ 0.48807119]
 [ 0.41988586]
 [ 0.76769016]]


In many models, we wish to simulate a random process while controlling the outcome. A random generator is, in this context, a random module that is random once but then stays the same. It is identified by a index

In [ ]:
rng = np.random.default_rng(1)

A =rng.normal(loc=50,scale=5,size=[3,2,2])
A_c = rng.choice(A.flat,size=[2,2], replace=True) # remember to flat!
print(A)
print(A_c)

rng_2 = np.random.default_rng() # no id, different every rerun but not within code

A = rng_2.normal(loc=50,scale=5,size=[3,2,2])
B= rng_2.normal(loc=50,scale=5,size=[3,2,2])
A_c = rng_2.choice(A.flat,size=[2,2], replace=True)
print(A)
print(A_c)

# try running multiple times!


[[[51.72792096 54.10809072]
  [51.65218538 43.48421384]]

 [[54.52677933 52.23187286]
  [47.31523382 52.90559052]]

 [[51.82286198 51.47066248]
  [50.14211121 52.73356493]]]
[[51.47066248 43.48421384]
 [52.23187286 51.47066248]]
[[[48.75800592 55.28167237]
  [46.88007332 48.74043497]]

 [[50.56628902 52.19748435]
  [50.07177455 62.67083721]]

 [[54.37960438 46.62084732]
  [55.5741003  51.59976076]]]
[[55.5741003  55.28167237]
 [62.67083721 62.67083721]]


As a final note, we may compute the mean and standard variance of a set ( array). These are the sample versions be the way. we may also choose mean across one row or column, depending on axis. 

In [ ]:
rng = np.random.default_rng(4)
A = rng.normal(loc=10,scale=5,size = [4,5])
print(A)
avg = np.average(A)
var = np.var(A)
std = np.std(A)
avg_col = np.average(A,axis=1)# 1 is row, while, 0 is column 
# if 3d then layer would be 2, row 1 and column 0)
print(avg,var,std,np.var(A,ddof=1),avg_col)


[[ 6.74104424  9.12641354 18.31861996 13.29573875  1.79301353]
 [ 9.97398368  6.8826813  10.74315762  1.95906108 11.20885938]
 [11.17690459 17.87813016 11.58322508 12.55273331  2.53441658]
 [21.26364562  0.42177221 15.50900928  8.35047963  5.59676741]]
9.845482846661076 31.699490594181718 5.6302300658305 33.36788483598076 [ 9.854966    8.15354861 11.14508194 10.22833483]
